//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashBoardPF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetIngresosConc
    {
        public int idSucursal { get; set; }
        public long Ticket { get; set; }
        public int idPlatillo { get; set; }
        public double Cantidad { get; set; }
        public double Precio { get; set; }
        public System.DateTime Fecha { get; set; }
    }
}
