//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashBoardPF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngresosConc
    {
        public int idSucursal { get; set; }
        public long Ticket { get; set; }
        public System.DateTime Fecha { get; set; }
        public double Total { get; set; }
        public string Tipo { get; set; }
        public string Pago { get; set; }
        public string idEmp { get; set; }
        public string idMesera { get; set; }
        public string Hora { get; set; }
        public string Moneda { get; set; }
        public Nullable<double> Valor { get; set; }
        public Nullable<double> CantDolar { get; set; }
        public Nullable<int> NoPersonas { get; set; }
        public string Maquina { get; set; }
    }
}
