//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashBoardPF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sucursales
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Colonia { get; set; }
        public string Direccion { get; set; }
        public string Estado { get; set; }
        public string Ciudad { get; set; }
        public string RFC { get; set; }
        public string Telefono { get; set; }
        public string Identificador { get; set; }
        public string Estatus { get; set; }
        public double IVA { get; set; }
        public Nullable<bool> Regimen { get; set; }
        public string RegIMSS { get; set; }
        public Nullable<int> IdBodega { get; set; }
        public string DiaPromocion { get; set; }
        public Nullable<bool> CeDis { get; set; }
        public string NombreComercial { get; set; }
        public byte[] Logotipo { get; set; }
        public string TelCa { get; set; }
        public Nullable<bool> Almacen { get; set; }
        public Nullable<bool> Tesoreria { get; set; }
        public Nullable<bool> SevDom { get; set; }
        public string SerieFacturacion { get; set; }
        public string RutaFactura { get; set; }
        public string CtaContpaqVenta { get; set; }
        public Nullable<int> IdentificarPolizas { get; set; }
    }
}
